<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testcases.LoginTestCase2" tests="2" time="3.451" ignored="4" failures="1" timestamp="24 Jun 2018 04:57:41 GMT" skipped="1" hostname="TMV-DEV-57" errors="0">
  <testcase name="logout" time="0.000" classname="testcases.LoginTestCase2">
    <skipped/>
  </testcase> <!-- logout -->
  <testcase name="login" time="3.451" classname="testcases.LoginTestCase2">
    <failure type="java.lang.AssertionError" message="expected [Search for your favorite vids - ManyVids] but found [OrangeHRM]">
      <![CDATA[java.lang.AssertionError: expected [Search for your favorite vids - ManyVids] but found [OrangeHRM]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at pages.LoginPage.verifyTitleBeforeLogin(LoginPage.java:47)
	at testcases.LoginTestCase2.login(LoginTestCase2.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="tearDownTestSuite" classname="pages.BaseClass">
    <skipped/>
  </testcase> <!-- tearDownTestSuite -->
  <testcase name="tearDownTestSuite" classname="pages.BaseClass">
    <skipped/>
  </testcase> <!-- tearDownTestSuite -->
  <testcase name="setupTestSuite" classname="pages.BaseClass">
    <skipped/>
  </testcase> <!-- setupTestSuite -->
  <testcase name="setupTestSuite" classname="pages.BaseClass">
    <skipped/>
  </testcase> <!-- setupTestSuite -->
</testsuite> <!-- testcases.LoginTestCase2 -->
